name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Delete docker trash
        continue-on-error: true
        run: |
          docker container rm -f -v t22_api
          docker container rm -f -v t22_db
          docker network rm t22_network
          docker image rm t22_api_image

      - name: Show docker state (before)
        run: |
          docker image ls
          docker network ls
          docker container ls

      - name: Build docker image
        run: docker-compose -f docker-compose.yml build

      - name: Run docker container
        run: docker-compose up -d

      - name: Show docker state (after)
        run: |
          docker image ls
          docker network ls
          docker container ls

      - name: Exec unit-tests
        continue-on-error: true
        run: docker exec --tty t22_api python -m unittest -v tests.py

      - name: Exec py-tests
        continue-on-error: true
        run: docker exec --tty t22_api pytest -v tests_pt.py
